name: handle-changelog
run-name: handling release notes
on: [push]
#  push:
#    branches:
#      - main
jobs:
  handle-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: chmod +x .github/workflows/handle_changelog.bash && ./.github/workflows/handle_changelog.bash
      shell: bash
