name: handle-changelog
run-name: handling release notes
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  handle-release-notes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Handle Changelog
      shell: bash
      run: chmod +x .github/workflows/handle_changelog.bash && ./.github/workflows/handle_changelog.bash
